import {getSession,signOut} from './auth.js';
let session=null,customers=[],selectedCustomer=null,currentImport=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=(p,o={})=>fetch(p,{...o,headers:{...(o.headers||{}),Authorization:`Bearer ${session.accessToken}`}});
const name=()=>session?.user?.user_metadata?.preferred_name||session?.user?.user_metadata?.name||session?.user?.email?.split('@')[0]||'there';
const initial=()=>name().trim().charAt(0).toUpperCase()||'K';
const fmt=n=>new Intl.NumberFormat().format(Number(n||0));
function polish(){const s=document.createElement('style');s.textContent=`:root{--known-ink:#202925;--known-muted:#6e7973;--known-line:#dfe4df;--known-paper:#f8f9f6;--known-green:#315d50;--known-soft:#edf3ee}html,body{background:var(--known-paper);color:var(--known-ink)}.sidebar{background:rgba(248,249,246,.97);border-right-color:var(--known-line)}.sidebar-note{display:none}.brand,.top-profile,.page-head h1{color:var(--known-ink)}.nav-item:hover,.nav-item.active{background:var(--known-soft);border-color:#dfe7e1;color:var(--known-ink)}.nav-item.active span{color:var(--known-green)}.global-search,.icon-button,.search-box,.stat-card,.panel{background:#fff;border-color:var(--known-line);box-shadow:0 2px 7px rgba(39,51,44,.05)}.primary-button{background:var(--known-ink)}.primary-button:hover{background:#2b3530}.eyebrow{color:var(--known-green)}.connection{color:#4f7e69;background:var(--known-soft);border-color:#cddfd5}.profile-avatar,.detail-avatar,.modal-profile-avatar{background:#e2eee6;color:var(--known-green)}.customer-context-row{display:grid;grid-template-columns:1fr auto;gap:5px;padding:14px 0;border-bottom:1px solid #e4e9e5}.customer-context-row strong{font-size:11px;color:#34413b}.customer-context-row small{font-size:9px;color:#89958e}.customer-context-row b{grid-column:1/-1;font-size:9px;color:#7c8982}.sidebar.collapsed{width:66px;padding-left:10px;padding-right:10px}.sidebar.collapsed .sidebar-top{justify-content:center}.sidebar.collapsed .brand{display:none}.sidebar.collapsed .nav-item{justify-content:center;padding-left:8px;padding-right:8px;font-size:0}.sidebar.collapsed .nav-item span{width:auto;font-size:16px}.sidebar.collapsed~.main{margin-left:66px}@media(max-width:760px){.sidebar{transform:translateX(-100%);box-shadow:12px 0 30px rgba(32,41,37,.08)}.sidebar.collapsed{transform:translateX(-100%);width:236px}.sidebar:not(.collapsed){transform:translateX(0)}.main,.sidebar.collapsed~.main{margin-left:0;padding:0 18px 35px}.sidebar-close{display:grid}.topbar{height:64px}.global-search{width:min(390px,65vw)}}`;document.head.appendChild(s)}
function modal(id){$('#modal-root').hidden=false;$$('.modal-card').forEach(x=>x.hidden=x.id!==id)}
function closeModal(){if($('#modal-root'))$('#modal-root').hidden=true;$$('.modal-card').forEach(x=>x.hidden=true);currentImport=null}
function view(v){$$('.view').forEach(x=>x.hidden=x.id!==`view-${v}`);$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='overview')overview();if(v==='customers')directory();if(v==='imported')imports()}
function setSidebar(open){const s=$('#sidebar');if(s)s.classList.toggle('collapsed',!open)}
function setupNav(){ $('#sidebar-close')?.addEventListener('click',()=>setSidebar(false)); $('#hamburger')?.addEventListener('click',()=>setSidebar(true));$$('.nav-item').forEach(b=>b.addEventListener('click',()=>{setSidebar(true);view(b.dataset.view)}));$$('[data-view]:not(.nav-item)').forEach(b=>b.addEventListener('click',()=>{setSidebar(true);view(b.dataset.view)}));$('#modal-backdrop')?.addEventListener('click',closeModal);$$('[data-close-modal]').forEach(b=>b.addEventListener('click',closeModal));$('#confirm-logout')?.addEventListener('click',async()=>{await signOut();location.href='./landing.html'});$('#profile-button')?.addEventListener('click',()=>modal('profile-modal'));$('#profile-logout')?.addEventListener('click',()=>modal('confirm-modal'));$('#customer-back')?.addEventListener('click',()=>{selectedCustomer=null;view('customers')});$('#shopify-coming')?.addEventListener('click',()=>modal('shopify-modal'))}
function profile(){const n=name(),i=initial();if($('#top-profile-name'))$('#top-profile-name').textContent=n;if($('#top-profile-avatar'))$('#top-profile-avatar').textContent=i;if($('#modal-profile-avatar'))$('#modal-profile-avatar').textContent=i;if($('#profile-modal-title'))$('#profile-modal-title').textContent=`Hi, ${n}`;if($('#modal-profile-email'))$('#modal-profile-email').textContent=session.user.email||''}
async function load(){const r=await api('/api/customers');if(!r.ok)throw Error('Unable to load customers');customers=await r.json();overview();directory()}
function overview(){const now=new Date();if($('#today-label'))$('#today-label').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now).toUpperCase();if($('#greeting'))$('#greeting').textContent=`${now.getHours()<12?'Good morning':now.getHours()<18?'Good afternoon':'Good evening'}, ${name()}.`;if($('#stat-customers'))$('#stat-customers').textContent=fmt(customers.length);if($('#stat-history'))$('#stat-history').textContent=customers.length?'Available':'—';if($('#stat-inbox'))$('#stat-inbox').textContent='0';if($('#recent-activity'))$('#recent-activity').innerHTML=customers.length?'<div class="empty-state">No open conversations yet.</div>':'<div class="empty-state">Import customer history to start building memory.</div>';const details=$('#customer-details-summary');if(details&&!selectedCustomer)details.innerHTML='<div class="empty-state">Select a customer to see their name, ID and order context.</div>'}
function directory(){const q=($('#customer-search')?.value||'').toLowerCase();const list=customers.filter(c=>[c.name,c.email,c.id].some(v=>String(v||'').toLowerCase().includes(q)));if($('#customer-count'))$('#customer-count').textContent=fmt(customers.length);const box=$('#customer-directory');if(!box)return;box.innerHTML='';if(!list.length){box.innerHTML='<div class="empty-state">No customers match your search.</div>';return}list.forEach(c=>{const b=document.createElement('button');b.className='directory-row';b.type='button';b.innerHTML=`<span class="directory-avatar">${(c.name||'?').charAt(0).toUpperCase()}</span><span class="directory-info"><strong>${escape(c.name||'Unnamed customer')}</strong><small>${escape(c.email||c.id)}</small></span>`;b.onclick=()=>select(c.id);box.appendChild(b)})}
function escape(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
async function select(id){const r=await api(`/api/workspace/${encodeURIComponent(id)}`);if(!r.ok)return;const d=await r.json();selectedCustomer=d.customer;$('#detail-avatar').textContent=(d.customer.name||'?').charAt(0).toUpperCase();$('#detail-name').textContent=d.customer.name||'Customer';$('#detail-meta').textContent=d.customer.email||'';$('#detail-email').textContent=d.customer.email||'—';$('#detail-id').textContent=d.customer.id||'—';$('#detail-orders').innerHTML=(d.orders||[]).map(o=>`<div class="order"><b>${escape(o.id||'Order')}</b><span class="status">${escape(o.status||'unknown')}</span><small>${escape((o.items||[]).map(x=>x?.name||x).join(', '))}</small></div>`).join('')||'<div class="empty-state">No order history.</div>';$('#detail-memory').innerHTML=(d.memory||[]).map(m=>`<article class="memory-item"><label>${escape(m.type||'MEMORY')}</label><p>${escape(m.content||'')}</p></article>`).join('')||'<div class="empty-state">No relevant memory surfaced yet.</div>';$('#memory-count').textContent=(d.memory||[]).length;const details=$('#customer-details-summary');if(details)details.innerHTML=`<div class="customer-context-row"><strong>${escape(d.customer.name||'Customer')}</strong><small>${escape(d.customer.id||'')}</small><b>${escape((d.orders||[])[0]?.id||'No order')}</b></div>`;view('customers')}
async function search(){const input=$('#global-search'),box=$('#search-results'),q=input?.value.trim();if(!input||!box)return;if(!q){box.hidden=true;return}box.innerHTML='<div class="search-empty">Searching…</div>';box.hidden=false;const r=await api(`/api/search?q=${encodeURIComponent(q)}`);if(!r.ok){box.innerHTML='<div class="search-empty">Search unavailable.</div>';return}const d=await r.json();box.innerHTML='';[...(d.customers||[]).map(c=>({label:c.name||'Customer',sub:c.email||c.id,id:c.id})),...(d.orders||[]).map(o=>({label:`Order ${o.id}`,sub:`Customer ${o.customer_id}`,id:o.customer_id}))].forEach(x=>{const b=document.createElement('button');b.className='search-result';b.innerHTML=`<strong>${escape(x.label)}</strong><small>${escape(x.sub)}</small>`;b.onclick=()=>{input.value='';box.hidden=true;select(x.id)};box.appendChild(b)});if(!box.children.length)box.innerHTML='<div class="search-empty">No customer or order found.</div>'}
function setupSearch(){let t;$('#global-search')?.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(search,180)});$('#customer-search')?.addEventListener('input',directory)}
async function imports(){const r=await api('/api/imports');if(!r.ok)return;const data=await r.json(),box=$('#imported-list');if(!box)return;box.innerHTML='';if(!data.length){box.innerHTML='<div class="empty-state">No CSV imports recorded yet.</div>';return}data.forEach(f=>{const row=document.createElement('div');row.className='imported-row';row.innerHTML=`<span class="import-file-icon">CSV</span><span><strong>${escape(f.name)}</strong><small>${fmt(f.customer_count)} customers · ${fmt(f.order_count)} orders</small></span><span class="row-actions"><button class="row-action rename">Rename</button><button class="row-action">Archive</button><button class="row-action danger">Delete</button></span>`;const [ren,arc,del]=row.querySelectorAll('button');ren.onclick=async()=>{const n=prompt('Rename CSV',f.name);if(!n||n===f.name)return;await api(`/api/imports/${f.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n})});imports()};arc.onclick=async()=>{if(confirm('Archive this import?')){await api(`/api/imports/${f.id}/archive`,{method:'PATCH'});imports()}};del.onclick=async()=>{if(confirm('Delete this import record?')){await api(`/api/imports/${f.id}`,{method:'DELETE'});imports()}};box.appendChild(row)})}
function setupImport(){const fi=$('#dashboard-csv-file'),next=$('#dashboard-csv-next'),sum=$('#dashboard-csv-summary'),status=$('#dashboard-csv-status');$('#new-import-button')?.addEventListener('click',()=>modal('import-modal'));if(!fi||!next)return;fi.onchange=async()=>{const f=fi.files?.[0];if(!f)return;currentImport={name:f.name,text:await f.text()};const r=await api('/api/imports/csv/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv_text:currentImport.text})});const d=await r.json();if(!r.ok){status.textContent=d.detail||'Could not inspect CSV';return}sum.hidden=false;sum.textContent=`${f.name} · ${fmt(d.row_count)} rows · ${fmt(d.customer_count)} customers · ${fmt(d.order_count)} orders`;next.disabled=false};next.onclick=async()=>{if(!currentImport)return;next.disabled=true;status.textContent='Importing…';const r=await api('/api/imports/csv/commit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv_text:currentImport.text,file_name:currentImport.name})});const d=await r.json();if(!r.ok){status.textContent=d.detail||'Import failed';next.disabled=false;return}closeModal();fi.value='';next.disabled=true;await load();await imports();view('customers')}}
function settings(){const a=$('#notify-import'),b=$('#notify-conversations');if(!a||!b)return;a.checked=localStorage.getItem('known.notify.import')!=='false';b.checked=localStorage.getItem('known.notify.conversations')!=='false';a.onchange=()=>localStorage.setItem('known.notify.import',a.checked);b.onchange=()=>localStorage.setItem('known.notify.conversations',b.checked)}
async function boot(){polish();session=await getSession();if(!session){location.href='./login.html';return}setupNav();profile();setupSearch();setupImport();settings();setSidebar(true);await load();view('overview')}
boot().catch(e=>{console.error(e);const x=$('#recent-activity');if(x)x.innerHTML=`<div class="empty-state">${escape(e.message||'Unable to initialize Known.')}</div>`})