import {getSession,signOut} from './auth.js';
let session=null,customers=[],selectedCustomer=null,currentImport=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const api=(p,o={})=>fetch(p,{...o,headers:{...(o.headers||{}),Authorization:`Bearer ${session.accessToken}`}});
const name=()=>session?.user?.user_metadata?.preferred_name||session?.user?.user_metadata?.name||session?.user?.email?.split('@')[0]||'there';
const initial=()=>name().trim().charAt(0).toUpperCase()||'K';
const fmt=n=>new Intl.NumberFormat().format(Number(n||0));
function modal(id){$('#modal-root').hidden=false;$$('.modal-card').forEach(x=>x.hidden=x.id!==id)}
function closeModal(){$('#modal-root').hidden=true;$$('.modal-card').forEach(x=>x.hidden=true);currentImport=null}
function view(v){$$('.view').forEach(x=>x.hidden=x.id!==`view-${v}`);$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='overview')overview();if(v==='customers')directory();if(v==='imported')imports();}
function sidebar(){const s=$('#sidebar');if(s.classList.contains('collapsed')){s.classList.remove('collapsed');s.dataset.expanded='true'}else s.classList.add('collapsed')}
function setupNav(){ $('#sidebar-toggle').onclick=sidebar; $$('[data-view]').forEach(b=>b.onclick=()=>{if($('#sidebar').classList.contains('collapsed'))$('#sidebar').classList.remove('collapsed');view(b.dataset.view)}); $('#modal-backdrop').onclick=closeModal;$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);$('#confirm-logout').onclick=async()=>{await signOut();location.href='./landing.html'};$('#profile-button').onclick=()=>modal('profile-modal');$('#profile-logout').onclick=()=>modal('confirm-modal');$('#customer-back').onclick=()=>{selectedCustomer=null;view('customers')};$('#shopify-coming').onclick=()=>modal('shopify-modal');if($('#email-connect'))$('#email-connect').onclick=()=>modal('email-modal')}
function profile(){const n=name(),i=initial();$('#top-profile-name').textContent=n;$('#top-profile-avatar').textContent=i;$('#modal-profile-avatar').textContent=i;$('#profile-modal-title').textContent=`Hi, ${n}`;$('#modal-profile-email').textContent=session.user.email||''}
async function load(){const r=await api('/api/customers');if(!r.ok)throw Error('Unable to load customers');customers=await r.json();overview();directory()}
function overview(){const now=new Date(),n=name();$('#today-label').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now).toUpperCase();$('#greeting').textContent=`${now.getHours()<12?'Good morning':now.getHours()<18?'Good afternoon':'Good evening'}, ${n}.`;$('#stat-customers').textContent=fmt(customers.length);$('#stat-history').textContent=customers.length?'Available':'—';$('#stat-inbox').textContent='0';$('#stat-import').textContent='';$('#stat-import-detail').textContent='';$('#recent-activity').innerHTML=customers.length?'<div class="empty-state">No open conversations yet.</div>':'<div class="empty-state">Import customer history to start building memory.</div>';if(!selectedCustomer)$('#customer-details').innerHTML='<div class="empty-state">Select a customer to see their name, ID and order context.</div>'}
function directory(){const q=($('#customer-search')?.value||'').toLowerCase();const list=customers.filter(c=>[c.name,c.email,c.id].some(v=>String(v||'').toLowerCase().includes(q)));$('#customer-count').textContent=fmt(customers.length);const box=$('#customer-directory');box.innerHTML='';if(!list.length){box.innerHTML='<div class="empty-state">No customers match your search.</div>';return}list.forEach(c=>{const b=document.createElement('button');b.className='directory-row';b.type='button';b.innerHTML=`<span class="directory-avatar">${(c.name||'?').charAt(0).toUpperCase()}</span><span class="directory-info"><strong>${escape(c.name||'Unnamed customer')}</strong><small>${escape(c.email||c.id)}</small></span>`;b.onclick=()=>select(c.id);box.appendChild(b)})}
function escape(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
async function select(id){const r=await api(`/api/workspace/${encodeURIComponent(id)}`);if(!r.ok)return;const d=await r.json();selectedCustomer=d.customer;$('#detail-avatar').textContent=(d.customer.name||'?').charAt(0).toUpperCase();$('#detail-name').textContent=d.customer.name||'Customer';$('#detail-meta').textContent=d.customer.email||'';$('#detail-email').textContent=d.customer.email||'—';$('#detail-id').textContent=d.customer.id||'—';$('#detail-orders').innerHTML=(d.orders||[]).map(o=>`<div class="order"><b>${escape(o.id||'Order')}</b><span class="status">${escape(o.status||'unknown')}</span><small>${escape((o.items||[]).map(x=>x?.name||x).join(', '))}</small></div>`).join('')||'<div class="empty-state">No order history.</div>';$('#detail-memory').innerHTML=(d.memory||[]).map(m=>`<article class="memory-item"><label>${escape(m.type||'MEMORY')}</label><p>${escape(m.content||'')}</p></article>`).join('')||'<div class="empty-state">No relevant memory surfaced yet.</div>';$('#memory-count').textContent=(d.memory||[]).length;$('#customer-details').innerHTML=`<div class="coverage-row"><div><strong>${escape(d.customer.name||'Customer')}</strong><small>${escape(d.customer.id||'')}</small></div><b>${escape((d.orders||[])[0]?.id||'No order')}</b></div>`;const actions=$('#customer-actions');if(actions){actions.innerHTML='<button class="row-action" id="archive-customer">Archive</button><button class="row-action danger" id="delete-customer">Delete</button>';$('#archive-customer').onclick=async()=>{if(!confirm('Archive this customer?'))return;await api(`/api/customers/${encodeURIComponent(id)}/archive`,{method:'PATCH'});await load();view('customers')};$('#delete-customer').onclick=async()=>{if(!confirm('Delete this customer permanently?'))return;await api(`/api/customers/${encodeURIComponent(id)}`,{method:'DELETE'});selectedCustomer=null;await load();view('customers')}}view('customers')}
async function search(){const input=$('#global-search'),box=$('#search-results'),q=input.value.trim();if(!q){box.hidden=true;return}box.innerHTML='<div class="search-empty">Searching…</div>';box.hidden=false;const r=await api(`/api/search?q=${encodeURIComponent(q)}`);if(!r.ok){box.innerHTML='<div class="search-empty">Search unavailable.</div>';return}const d=await r.json();box.innerHTML='';[...(d.customers||[]).map(c=>({label:c.name||'Customer',sub:c.email||c.id,id:c.id})),...(d.orders||[]).map(o=>({label:`Order ${o.id}`,sub:`Customer ${o.customer_id}`,id:o.customer_id}))].forEach(x=>{const b=document.createElement('button');b.className='search-result';b.innerHTML=`<strong>${escape(x.label)}</strong><small>${escape(x.sub)}</small>`;b.onclick=()=>{input.value='';box.hidden=true;select(x.id)};box.appendChild(b)});if(!box.children.length)box.innerHTML='<div class="search-empty">No customer or order found.</div>'}
function setupSearch(){let t;$('#global-search').oninput=()=>{clearTimeout(t);t=setTimeout(search,180)};$('#customer-search').oninput=directory}
async function imports(){const r=await api('/api/imports');if(!r.ok)return;const data=await r.json(),box=$('#imported-list');box.innerHTML='';if(!data.length){box.innerHTML='<div class="empty-state">No CSV imports recorded yet.</div>';return}data.forEach(f=>{const row=document.createElement('div');row.className='imported-row';row.innerHTML=`<span class="import-file-icon">CSV</span><span><strong>${escape(f.name)}</strong><small>${fmt(f.customer_count)} customers · ${fmt(f.order_count)} orders</small></span><span class="row-actions"><button class="row-action rename">Rename</button><button class="row-action">Archive</button><button class="row-action danger">Delete</button></span>`;const [ren,arc,del]=row.querySelectorAll('button');ren.onclick=async()=>{const n=prompt('Rename CSV',f.name);if(!n||n===f.name)return;await api(`/api/imports/${f.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n})});imports()};arc.onclick=async()=>{if(confirm('Archive this import?')){await api(`/api/imports/${f.id}/archive`,{method:'PATCH'});imports()}};del.onclick=async()=>{if(confirm('Delete this import record?')){await api(`/api/imports/${f.id}`,{method:'DELETE'});imports()}};box.appendChild(row)})}
function setupImport(){const fi=$('#dashboard-csv-file'),next=$('#dashboard-csv-next'),sum=$('#dashboard-csv-summary'),status=$('#dashboard-csv-status');$('#new-import-button').onclick=()=>modal('import-modal');fi.onchange=async()=>{const f=fi.files?.[0];if(!f)return;currentImport={name:f.name,text:await f.text()};const r=await api('/api/imports/csv/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv_text:currentImport.text})});const d=await r.json();if(!r.ok){status.textContent=d.detail||'Could not inspect CSV';return}sum.hidden=false;sum.textContent=`${f.name} · ${fmt(d.row_count)} rows · ${fmt(d.customer_count)} customers · ${fmt(d.order_count)} orders`;next.disabled=false};next.onclick=async()=>{if(!currentImport)return;next.disabled=true;status.textContent='Importing…';const r=await api('/api/imports/csv/commit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv_text:currentImport.text,file_name:currentImport.name})});const d=await r.json();if(!r.ok){status.textContent=d.detail||'Import failed';next.disabled=false;return}closeModal();fi.value='';next.disabled=true;await load();await imports();view('customers')}}
function settings(){const a=$('#notify-import'),b=$('#notify-conversations');a.checked=localStorage.getItem('known.notify.import')!=='false';b.checked=localStorage.getItem('known.notify.conversations')!=='false';a.onchange=()=>localStorage.setItem('known.notify.import',a.checked);b.onchange=()=>localStorage.setItem('known.notify.conversations',b.checked)}
async function boot(){session=await getSession();if(!session){location.href='./login.html';return}setupNav();profile();setupSearch();setupImport();settings();await load();view('overview')}
boot().catch(e=>{console.error(e);const x=$('#recent-activity');if(x)x.innerHTML=`<div class="empty-state">${escape(e.message||'Unable to initialize Known.')}</div>`})
