import { getSession, signOut } from "./auth.js";

const API = window.KNOWN_API_URL || "";
let session = null;
let sessionId = null;
let selectedCustomer = null;
let selectedOrders = [];
const $ = (selector) => document.querySelector(selector);
const messages = $("#messages");
const form = $("#composer");
const input = $("#message");
function apiUrl(path) { return `${API}${path}`; }
function addMessage(label, text, className) { const el=document.createElement("div"); el.className=`msg ${className}`; const small=document.createElement("small"); small.textContent=label; const p=document.createElement("p"); p.textContent=text; el.append(small,p); messages.appendChild(el); messages.scrollTop=messages.scrollHeight; }
function emptyState(text) { messages.innerHTML=""; const el=document.createElement("div"); el.className="empty-state"; el.textContent=text; messages.appendChild(el); }
function renderConversation(items) { messages.innerHTML=""; if(!items?.length)return emptyState("No messages in this conversation yet."); for(const item of items)addMessage(item.role==="assistant"?"KNOWN":(selectedCustomer?.name||"CUSTOMER").toUpperCase(),item.content,item.role==="assistant"?"agent-msg":"customer-msg"); }
function renderCustomers(customers) { const list=$("#customer-list"); list.innerHTML=""; if(!customers.length){const empty=document.createElement("div");empty.className="empty-state";empty.textContent="No customers imported yet.";list.appendChild(empty);return;} for(const customer of customers){const button=document.createElement("button");button.className="customer";button.dataset.customerId=customer.id;const initial=document.createElement("span");initial.textContent=(customer.name||"C").charAt(0).toUpperCase();const info=document.createElement("div");const strong=document.createElement("strong");strong.textContent=customer.name;const small=document.createElement("small");small.textContent=`${customer.tier||"standard"} · ${customer.email||"No email"}`;info.append(strong,small);button.append(initial,info);button.addEventListener("click",()=>selectCustomer(customer));list.appendChild(button);} }
function renderWorkspace(data) { selectedCustomer=data.customer; selectedOrders=data.orders||[]; $("#customer-detail-name").textContent=data.customer.name; $("#customer-detail-tier").textContent=`${data.customer.tier||"standard"} customer`; $("#customer-detail-email").textContent=data.customer.email||"No email"; $("#customer-detail-id").textContent=data.customer.id; const orderBody=$("#orders"); orderBody.innerHTML=""; if(!selectedOrders.length)orderBody.innerHTML='<div class="empty-state">No orders found for this customer.</div>'; else for(const order of selectedOrders){const row=document.createElement("div");row.className="order";const id=document.createElement("b");id.textContent=order.id;const status=document.createElement("span");status.className=`status ${order.status==="delivered"?"delivered":"delayed"}`;status.textContent=order.status;const meta=document.createElement("small");meta.textContent=`$${Number(order.total||0).toFixed(2)} · ${(order.items||[]).join(", ")||"No line items"}`;row.append(id,status,meta);orderBody.appendChild(row);} const memoryBody=$("#memory");memoryBody.innerHTML="";const memories=data.memory||[];if(!memories.length)memoryBody.innerHTML='<div class="empty-state">No relevant memory found.</div>';else for(const memory of memories.slice(0,8)){const article=document.createElement("article");const label=document.createElement("label");label.textContent=memory.type||"MEMORY";const text=document.createElement("p");text.textContent=memory.content||"";article.append(label,text);memoryBody.appendChild(article);}const source=document.createElement("small");source.className="source";source.textContent=data.memory_available?"Retrieved from Sibyl Memory":"Sibyl Memory unavailable";memoryBody.appendChild(source);$(".memory-count").textContent=String(memories.length);$("#workspace").hidden=false;$("#onboarding").hidden=true;$("header h1").textContent=data.customer.name;$("#header-meta").textContent=`${data.customer.tier||"standard"} · ${data.customer.email||"No email"}`;input.placeholder=`Reply to ${data.customer.name.split(" ")[0]}…`;}
async function authenticatedFetch(path,options={}){if(!session)return null;let response=await fetch(apiUrl(path),{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${session.accessToken}`}});if(response.status!==401)return response;session=await getSession();if(!session){await signOut();location.href="./login.html";return null;}return fetch(apiUrl(path),{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${session.accessToken}`}});}
async function loadConversation(customer,newSession=false){if(newSession){sessionId=null;renderConversation([]);$("#session").textContent="New conversation";return;}const id=sessionId||localStorage.getItem(`known.session.${customer.id}`);if(!id){sessionId=null;renderConversation([]);$("#session").textContent="No conversation yet";return;}const response=await authenticatedFetch(`/api/sessions/${encodeURIComponent(id)}?customer_id=${encodeURIComponent(customer.id)}`);if(!response)return;if(response.status===404){localStorage.removeItem(`known.session.${customer.id}`);sessionId=null;renderConversation([]);$("#session").textContent="No conversation yet";return;}if(!response.ok)throw new Error(`Unable to load conversation (${response.status})`);const data=await response.json();sessionId=data.session_id;localStorage.setItem(`known.session.${customer.id}`,sessionId);renderConversation(data.messages||[]);$("#session").textContent=`Persistent · ${data.updated_at}`;}
async function loadWorkspace(customer){const response=await authenticatedFetch(`/api/workspace/${encodeURIComponent(customer.id)}`);if(!response)return;if(!response.ok)throw new Error(`Unable to load customer (${response.status})`);const data=await response.json();renderWorkspace(data);document.querySelectorAll(".customer").forEach(node=>node.classList.toggle("active",node.dataset.customerId===customer.id));await loadConversation(customer);}
async function selectCustomer(customer){try{await loadWorkspace(customer);}catch(error){emptyState(error.message||"Unable to load customer.");}}
async function loadCustomers(){const response=await authenticatedFetch("/api/customers");if(!response)return;if(!response.ok)throw new Error(`Unable to load customers (${response.status})`);const customers=await response.json();renderCustomers(customers);if(!customers.length){$("#workspace").hidden=true;$("#onboarding").hidden=false;return;}await loadWorkspace(customers[0]);}
async function loadShopifyStatus(){const response=await authenticatedFetch("/api/shopify/status");if(!response)return false;if(!response.ok)throw new Error("Unable to check Shopify connection.");const data=await response.json();if(data.connected){$("#connection-status").textContent=`Connected · ${data.installation.shop_name||data.installation.shop_domain}`;$("#onboarding").hidden=true;await loadCustomers();return true;}$("#connection-status").textContent="Not connected";$("#onboarding").hidden=false;return false;}
$("#shopify-form").addEventListener("submit",async(event)=>{event.preventDefault();const button=event.currentTarget.querySelector("button"),status=$("#shopify-status");button.disabled=true;status.textContent="Starting Shopify authorization…";try{const response=await authenticatedFetch("/api/shopify/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({shop_domain:$("#shop-domain").value})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Unable to connect Shopify.");location.href=data.authorization_url;}catch(error){status.textContent=error.message||"Unable to connect Shopify.";button.disabled=false;}});
form.addEventListener("submit",async(event)=>{event.preventDefault();if(!selectedCustomer)return;const message=input.value.trim();if(!message)return;input.value="";addMessage(`${selectedCustomer.name.toUpperCase()} · NOW`,message,"customer-msg");const button=form.querySelector("button");button.disabled=true;button.textContent="…";try{const response=await authenticatedFetch("/api/support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer_id:selectedCustomer.id,message,conversation_id:sessionId})});const data=await response.json();if(!response.ok)throw new Error(data.detail||`Support request failed (${response.status})`);sessionId=data.session_id;localStorage.setItem(`known.session.${selectedCustomer.id}`,sessionId);$("#session").textContent=`Persistent · ${data.persistence}`;renderConversation(data.conversation||[]);}catch(error){addMessage("SYSTEM",error.message||"Unable to reach Known.","agent-msg");}finally{button.disabled=false;button.textContent="Send";input.focus();}});
(async function bootstrap(){try{session=await getSession();if(!session){location.href="./login.html";return;}const params=new URLSearchParams(location.search);if(params.get("shopify")==="error")$("#shopify-status").textContent="Shopify connection failed. Check the app configuration and try again.";if(params.get("imported")==="1"){await loadCustomers();$("#connection-status").textContent="Customer memory ready";return;}await loadShopifyStatus();}catch(error){emptyState(error.message||"Unable to initialize Known.");}})();
